### ISSUE TITLE
Remove poltergeist dependency

### ISSUE THREAD

**Issue by jekuno** [rprt/rspec-page-regression#10]
Users of your gem who don't use poltergeist (but selenium) don't want to get poltergeist installed as a dependency. Therefore I'd suggest to remove the line `spec.add_dependency "poltergeist"` from the gemspec.

**Comment by ronen** [comment]
Yeah, that makes sense.  The gem and hence the README were written for poltergeist first and selenium as an afterthought.  But selenium should be promoted as a first-class option alongside poltergeist; both by the dependency change you suggest and by cleaning up the README.

This would technically be a breaking change, so would require a major version bump.  Could introduce that in conjunction with #9 and #11, if you're planning on implementing those.

As always, I'm happy to accept a PR!
