### ISSUE TITLE
Images are slightly different sizes on CI

### ISSUE THREAD

**Issue by tubbo** [rprt/rspec-page-regression#33]
This is a great idea, but we're having trouble nailing down a particular problem when the images are rendered on CI. We keep getting test failures with the following error message:

```
Test image size 1050x1127 does not match expectation 1050x1125
```

This isn't consistent at all, sometimes they're 2px off and sometimes they're more:

```
Test image size 320x1692 does not match expectation 320x1672
```

Any guesses as to what is causing this? We're using Poltergeist as our Capybara JS driver, if that makes a difference. Developers run this suite locally on Mac OS X, and the CI server is using Ubuntu Linux. Let me know if I can provide any additional information (including source code to the tests).

**Comment by jekuno** [comment]
Do you have any asynchronous JavaScript which alters the page and might not have been finished when taking the screenshot?

**Comment by ronen** [comment]
@tubbo, if @jekuno's suggestion doesn't help, it's possible that it's platform-specific behavior of phantomjs.   

If you visually compare the test and expected images, can you see what the differences are?

One problem that might hit you is that fonts may not be consistent between OS X and Linux.  See, e.g. [Besting PhantomJS Font Problems](https://medium.com/@stockholmux/besting-phantomjs-font-problems-ee22795f5c0b#.qelx5b1te) or [PhantomJS With WOFF Support]((https://blog.42mate.com/phantomjs-with-woff-support/).  I'm not sure whether that would account for different images sizes.

If the relevant parts of images are the same except for extra pixels around the edge, the upcoming version 1.0 of spec-page-regression will let you choose which parts to compare.  @jekuno, @paresharma -- any thoughts on when 1.0 will be ready to release?
